#!/bin/bash
rm -rf asan_result.log 
MCTester_ASAN 0 &> /dev/null
tests=$?
echo "Total Tests: $tests" 
for i in $(seq 1 $tests)
do
    echo "Executing Test $i"
    echo "=================================================================================================================================" >>asan_result.log 2>&1
    echo "== Starting Test $i" >>asan_result.log 2>&1
    echo "=================================================================================================================================" >>asan_result.log 2>&1
    MCTester_ASAN $i $i >>asan_result.log 2>&1
    echo "=================================================================================================================================" >>asan_result.log 2>&1
done
