#!/bin/bash
rm -rf dr_m_result.log 
MCTester 0 &> /dev/null
tests=$?
echo "Total Tests: $tests" 
for i in $(seq 1 $tests)
do
    echo "Executing Test $i"
    echo "=================================================================================================================================" >>dr_m_result.log 2>&1
    echo "== Starting Test $i" >>dr_m_result.log 2>&1
    echo "=================================================================================================================================" >>dr_m_result.log 2>&1
    /x01/exd10/DrMemory-Linux-1.10.0-2/bin/drmemory -- MCTester $i $i >>dr_m_result.log 2>&1
    echo "=================================================================================================================================" >>dr_m_result.log 2>&1
done
